[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.profiling-generate]
inherits = "release"
rustflags = ["-C", "profile-generate=/tmp/pgo-data"]

[profile.profiling-use]
inherits = "release"
rustflags = ["-C", "profile-use=/tmp/pgo-data/"]
