# cargo build --profile profiling-generate --features openblas-faer
# then run ./target/release/genomic_pca
# llvm-profdata merge -o /tmp/pgo-data/merged.profdata /tmp/pgo-data
# cargo build --profile profiling-use --features openblas-faer

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.profiling-generate]
inherits = "release"
rustflags = ["-C", "profile-generate=/tmp/pgo-data"]

[profile.profiling-use]
inherits = "release"
# This points to the specific file that llvm-profdata will create
rustflags = ["-C", "profile-use=/tmp/pgo-data/merged.profdata"]
