name: Generate getdoc Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  generate_getdoc_report:
    name: Generate getdoc Report
    runs-on: ubuntu-latest
    if: "github.event_name == 'pull_request' || !contains(github.event.head_commit.message, 'Merge pull request #')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain
        id: install_rust
    - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
          
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        id: cache-cargo-deps
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deps-
            
      - name: Output Cargo Dependencies Cache Info
        run: echo "Cargo dependencies cache hit ${{ steps.cache-cargo-deps.outputs.cache-hit }}"
          
      - name: Install getdoc
        run: cargo install getdoc --locked
        
      - name: Run getdoc
        run: getdoc
        
      - name: Display report.md
        run: cat report.md
